---
title: "Analyse Bowling Model"
output: html_notebook
---

```{r get model}

filename <- "Saved Models/RC_1200it_4ch_449obs.rds"

current_model <- readRDS(filename)

```

```{r print}

current_model %>% print(pars=c("theta", "delta", "alpha1", "alpha2", "nu", "xi", "zeta", "omega"))

```

```{r print2}

current_model %>% summary() %>% .$summary %>% .[, "n_eff"] %>% sort() %>% .[1:10]

```

```{r stuff}

params_ncp80 <- as.data.frame(extract(current_model, permuted=FALSE))
names(params_ncp80) <- gsub("chain:1.", "", names(params_ncp80), fixed = TRUE)
names(params_ncp80) <- gsub("[", ".", names(params_ncp80), fixed = TRUE)
names(params_ncp80) <- gsub("]", "", names(params_ncp80), fixed = TRUE)
params_ncp80$iter <- 1:50

par(mar = c(4, 4, 0.5, 0.5))
plot(params_ncp80$iter, log(params_ncp80$sigma2_theta.1), pch=16, cex=0.8,
     xlab="Iteration", ylab="log(sigma2_theta.1)", ylim=c(-6, 4))

divergent <- get_sampler_params(current_model, inc_warmup=FALSE)[[1]][,'divergent__']
params_ncp80$divergent <- divergent

div_params_ncp <- params_ncp80[params_ncp80$divergent == 1,]
nondiv_params_ncp <- params_ncp80[params_ncp80$divergent == 0,]

par(mar = c(4, 4, 0.5, 0.5))
plot(nondiv_params_ncp$theta.1, log(nondiv_params_ncp$sigma2_theta.1),
     xlab="theta.1", ylab="log(sigma2_theta.1)", xlim=c(-2, 7), ylim=c(-3,2),
     pch=16, cex=0.8)
points(div_params_ncp$theta.1, log(div_params_ncp$sigma2_theta.1),
       col="green", pch=16, cex=0.8)

```

```{r visualise mixing}

stan_trace(current_model, pars=c("theta"))
stan_trace(current_model, pars=c("mu_theta", "sigma2_theta"))
stan_trace(current_model, pars=c("delta"))
stan_trace(current_model, pars=c("sigma2_delta"))
stan_trace(current_model, pars=c("alpha1", "alpha2"))
stan_trace(current_model, pars=c("zeta", "nu"))
stan_trace(current_model, pars=c("xi"))
stan_trace(current_model, pars=c("omega"))

```

```{r visualise densities}

stan_dens(current_model, pars=c("theta"))
stan_dens(current_model, pars=c("mu_theta", "sigma2_theta"))
stan_dens(current_model, pars=c("delta"))
stan_dens(current_model, pars=c("sigma2_delta"))
stan_dens(current_model, pars=c("alpha1", "alpha2"))
stan_dens(current_model, pars=c("zeta", "nu"))
stan_dens(current_model, pars=c("xi"))
stan_dens(current_model, pars=c("omega"))

```
